### ISSUE TITLE
DX Pain points

### ISSUE THREAD

**Issue by madou** [element-motion/element-motion#145]
- Destination motion doesn't throw a nice error if its ref is missing
- Passing ref should blow up if its not a HTML element

**Comment by walesey** [comment]
use with react-popper is quite difficult.

**Comment by jackbrown** [comment]
minor; docs for `innerRef` with `styled-components@^3` would be helpful

**Comment by madou** [comment]
reveal doesn't play nicely with some padding/margin/border box etc. fucks up the height/width calcs.

**Comment by madou** [comment]
merged some stuff to make initial dx a bit better.
