### ISSUE TITLE
Random Question 😬

### ISSUE THREAD

**Issue by gagan0723** [element-motion/element-motion#159]
Is something like this possible https://twitter.com/maxlynch/status/1141786219149438976, except the gesture?

**Comment by madou** [comment]
Hi there!

Yeah I think so, using the Scale, InverseScale, and Translate components.
The cross fade part might be troublesome atm.

I can make an example in a few hours if you'd like.

**Comment by madou** [comment]
well I got _something_ like it working but it isn't great. i'll investigate why it's not working fantastically. will have to dig into the individual motions :)

One problem is #96, but there's also just some positioning that isn't working great.

https://codesandbox.io/s/frosty-bash-l5ri7

🤷‍♂

**Comment by gagan0723** [comment]
That looks great. Thanks a lot for your time and effort.😊
